# Generated by Django 3.1.1 on 2020-12-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvideo',
            name='age',
            field=models.DateField(verbose_name='Дата выхода видео'),
        ),
    ]
