# Generated by Django 3.1.1 on 2020-12-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20201228_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvideo',
            name='date_realise',
        ),
        migrations.RemoveField(
            model_name='carvideo',
            name='text_date_realise',
        ),
    ]
