# Generated by Django 3.1.1 on 2021-01-05 18:00

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20201228_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carvideo',
            options={'ordering': ['brand'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AlterField(
            model_name='carvideo',
            name='car',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='head.car', verbose_name='Модель авто'),
        ),
    ]
