# Generated by Django 3.1.1 on 2021-01-18 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_auto_20210105_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='history_brand',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carvideo',
            name='number_of_views',
            field=models.IntegerField(verbose_name='Количество просмотров'),
        ),
    ]
