# Generated by Django 3.1.1 on 2021-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_auto_20210118_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='history_brand',
            field=models.TextField(verbose_name='История марки'),
        ),
    ]
