# Generated by Django 3.1.1 on 2021-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20210118_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='history_brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='history',
            field=models.TextField(default='', verbose_name='История марки'),
            preserve_default=False,
        ),
    ]
