# Generated by Django 3.1.1 on 2021-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0008_auto_20210118_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='history',
            field=models.TextField(null=True, verbose_name='История марки'),
        ),
    ]
