# Generated by Django 3.1.1 on 2021-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0010_auto_20210119_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='history',
            field=models.TextField(blank=True, default='', null=True, verbose_name='История марки'),
        ),
    ]
