# Generated by Django 3.1.1 on 2021-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0017_auto_20210318_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
