# Generated by Django 3.2 on 2021-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0018_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Описание статьи'),
        ),
    ]
